/* Local prototype: IndexedDB portfolios, per-browser reactions. No server publication. */
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeImage=v=>/^(https?:\/\/|data:image\/(png|jpeg|webp);base64,|assets\/)/i.test(v||'')?v:'assets/images/home-category-apartment.png';
let local=[],items=[],savedOnly=false,selected=null,previews=[],busy=false;
let marks={};try{marks=JSON.parse(localStorage.getItem('sl-case-marks-v1')||'{}')||{};}catch{}
const dbReady=new Promise((resolve,reject)=>{const r=indexedDB.open('spacelink-cases',1);r.onupgradeneeded=()=>r.result.createObjectStore('cases',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
dbReady.catch(()=>{});
async function db(mode,action){const d=await dbReady;return new Promise((resolve,reject)=>{const tx=d.transaction('cases',mode),r=action(tx.objectStore('cases'));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
const owner=()=>{const s=window.AppState;return s.partnerLoggedIn?(s.partners||[]).find(p=>p.name===s.partnerName&&p.status==='active'):null;};
function collect(){const existing=(window.AppState.partners||[]).filter(p=>p.status==='active').flatMap(p=>(p.portfolios||[]).filter(c=>!c.isDraft).map(c=>({...c,id:'existing:'+p.id+':'+(c.id||c.title),partner:p.name,region:c.region||'지역 미등록',category:c.category||'리모델링',photos:[c.img,...(c.scenes||[]).map(s=>s.img)].filter((v,i,a)=>v&&a.indexOf(v)===i),example:true})));return [...local.filter(c=>(window.AppState.partners||[]).some(p=>p.id===c.owner&&p.status==='active')),...existing];}
function reaction(c,kind){return !!marks[c.id]?.[kind];}
function controls(c){return `<button data-action="like" data-id="${esc(c.id)}" aria-pressed="${reaction(c,'like')}">좋아요 ${Number(c.likes||0)+(reaction(c,'like')?1:0)}</button><button data-action="save" data-id="${esc(c.id)}" aria-pressed="${reaction(c,'save')}">${reaction(c,'save')?'스크랩됨':'스크랩'}</button>`;}
function render(){items=collect();const q=$('cases-search').value.trim().toLowerCase(),cat=$('cases-category').value;let rows=items.filter(c=>(!q||[c.title,c.partner,c.region,c.desc].join(' ').toLowerCase().includes(q))&&(!cat||c.category===cat)&&(!savedOnly||reaction(c,'save')));rows.sort($('cases-sort').value==='popular'?(a,b)=>(Number(b.likes||0)+Number(reaction(b,'like')))-(Number(a.likes||0)+Number(reaction(a,'like'))):(a,b)=>Number(b.created||0)-Number(a.created||0)||String(b.completed||'').localeCompare(String(a.completed||'')));$('cases-status').textContent=`${rows.length}개의 시공사례`;
$('cases-grid').innerHTML=rows.length?rows.map(c=>`<article class="case-card"><button class="case-open" data-action="open" data-id="${esc(c.id)}"><img loading="lazy" src="${esc(safeImage(c.photos[0]))}" alt="${esc(c.title)}"><span class="case-meta">${esc(c.category)} · ${esc(c.region)}${c.pyung?' · '+esc(c.pyung)+'평':''}${c.example?' · 예시':''}</span><h2>${esc(c.title)}</h2><span class="case-partner">${esc(c.partner)}</span></button><div class="case-actions">${controls(c)}</div></article>`).join(''):'<div class="cases-empty"><h2>아직 표시할 시공사례가 없어요</h2><p>검색 조건을 변경하거나 마음에 드는 사례를 스크랩해 주세요.</p></div>';}
async function renderPage(){try{local=await db('readonly',s=>s.getAll());render();}catch{render();$('cases-status').textContent='브라우저 저장소를 사용할 수 없습니다. 등록 기능을 사용하려면 저장소 설정을 확인해 주세요.';}}
function detail(id){const c=items.find(x=>x.id===id);if(!c)return;selected=id;$('cases-detail-content').innerHTML=`<span class="cases-eyebrow">${esc(c.category)}${c.example?' · 예시 포트폴리오':''}</span><h2>${esc(c.title)}</h2><p>${esc(c.partner)} · ${esc(c.region)}${c.pyung?' · '+esc(c.pyung)+'평':''}${c.completed?' · 완료 '+esc(c.completed):''}</p><div class="case-actions">${controls(c)}</div><p class="case-description">${esc(c.desc)}</p><div class="case-gallery">${c.photos.map((src,i)=>`<figure><img src="${esc(safeImage(src))}" alt="${esc(c.title)} 사진 ${i+1}" loading="lazy"></figure>`).join('')}</div><button class="cases-primary" data-action="partner">파트너 둘러보기</button>${c.owner&&owner()?.id===c.owner?'<button data-action="delete">내 시공사례 삭제</button>':''}`;if(!$('cases-detail').open)$('cases-detail').showModal();}
async function handle(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;if(a==='open')return detail(id);if(a==='partner'){$('cases-detail').close();switchPanel('partner-search-panel');return;}if(a==='delete'){const c=items.find(x=>x.id===selected);if(!c||!c.owner||owner()?.id!==c.owner)return;if(!confirm('이 브라우저에 등록한 시공사례를 삭제할까요?'))return;try{await db('readwrite',s=>s.delete(c.id));local=local.filter(x=>x.id!==c.id);$('cases-detail').close();render();}catch{$('cases-status').textContent='삭제하지 못했습니다. 다시 시도해 주세요.';}return;}const c=items.find(x=>x.id===id);if(!c)return;const key=a==='like'?'like':'save',next={...marks,[id]:{...marks[id],[key]:!marks[id]?.[key]}};try{localStorage.setItem('sl-case-marks-v1',JSON.stringify(next));marks=next;render();if($('cases-detail').open)detail(selected);}catch{$('cases-status').textContent='저장 공간이 부족해 반영하지 못했습니다.';}}
$('cases-grid').addEventListener('click',handle);$('cases-detail-content').addEventListener('click',handle);
for(const id of ['cases-search','cases-category','cases-sort'])$(id).addEventListener(id==='cases-search'?'input':'change',render);
$('cases-saved').onclick=()=>{savedOnly=!savedOnly;$('cases-saved').setAttribute('aria-pressed',savedOnly);render();};
$('cases-reset').onclick=()=>{$('cases-search').value='';$('cases-category').value='';$('cases-sort').value='new';savedOnly=false;$('cases-saved').setAttribute('aria-pressed','false');render();};
document.querySelectorAll('.cases-close').forEach(b=>b.onclick=()=>{if(!busy)b.closest('dialog').close();});
$('cases-upload').onclick=()=>{if(!owner()){$('cases-status').textContent='활성 파트너 계정으로 로그인한 후 등록할 수 있어요.';handleB2BNavClick();return;}$('cases-form-status').textContent='';const today=new Date();$('cases-form').elements.completed.max=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');$('cases-editor').showModal();};
const files=()=>Array.from($('cases-form').elements.photos.files);
function validate(list){if(!list.length||list.length>8)throw Error('사진을 1~8장 선택해 주세요.');if(list.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024))throw Error('사진당 5MB 이하의 JPG·PNG·WebP 파일을 선택해 주세요.');}
$('cases-form').elements.photos.onchange=()=>{previews.forEach(URL.revokeObjectURL);previews=[];$('cases-photo-preview').innerHTML='';try{validate(files());previews=files().map(f=>URL.createObjectURL(f));$('cases-photo-preview').innerHTML=previews.map((u,i)=>`<img src="${u}" alt="선택 사진 ${i+1}">`).join('');$('cases-form-status').textContent='';}catch(e){$('cases-form-status').textContent=e.message;}};
function read(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>resolve(r.result);im.onerror=()=>reject(Error('읽을 수 없는 이미지가 있습니다.'));im.src=r.result;};r.onerror=()=>reject(Error('사진을 읽지 못했습니다.'));r.readAsDataURL(file);});}
$('cases-editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('cases-form').onsubmit=async e=>{e.preventDefault();if(busy||!e.currentTarget.reportValidity())return;const partner=owner();if(!partner){$('cases-form-status').textContent='파트너 로그인이 필요합니다.';return;}const form=e.currentTarget,data=new FormData(form),button=form.querySelector('[type=submit]');try{if(!data.get('consent'))throw Error('사진 공개 권한과 완료 현장 여부를 확인해 주세요.');validate(files());if(!data.get('title').trim()||!data.get('desc').trim()||!data.get('region').trim())throw Error('제목, 지역, 내용을 입력해 주세요.');if(!/^\d{4}-\d{2}-\d{2}$/.test(data.get('completed'))||!Number.isFinite(Date.parse(data.get('completed'))))throw Error('공사 완료일을 입력해 주세요.');if(!(Number(data.get('pyung'))>=1&&Number(data.get('pyung'))<=10000))throw Error('면적은 1~10,000평 사이로 입력해 주세요.');if(new Date(data.get('completed')+'T00:00:00')>new Date())throw Error('완료일은 오늘 이전으로 선택해 주세요.');busy=true;button.disabled=true;$('cases-form-status').textContent='사진을 저장하고 있어요…';const photos=await Promise.all(files().map(read));if(owner()?.id!==partner.id)throw Error('로그인 계정이 변경되었습니다. 다시 시도해 주세요.');const c={id:'local:'+crypto.randomUUID(),owner:partner.id,partner:partner.name,title:data.get('title').trim(),desc:data.get('desc').trim(),region:data.get('region').trim(),category:data.get('category'),pyung:Number(data.get('pyung')),completed:data.get('completed'),created:Date.now(),photos,likes:0};await db('readwrite',s=>s.put(c));local.unshift(c);form.reset();previews.forEach(URL.revokeObjectURL);previews=[];$('cases-photo-preview').innerHTML='';$('cases-editor').close();$('cases-reset').click();detail(c.id);}catch(err){$('cases-form-status').textContent=err.name==='QuotaExceededError'?'저장 공간이 부족합니다. 사진 크기를 줄여 주세요.':err.message||'저장하지 못했습니다.';}finally{busy=false;button.disabled=false;}};
window.renderCasesPage=renderPage;
})();
